name: billiard_club_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_product_card: ^0.0.2
  shared_preferences: ^2.3.3
  marquee: ^2.3.0
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  intl: ^0.20.2
  flutter_svg: ^1.1.6
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/pool-cue-svgrepo-com.svg
    - lib/images/pool-table-svgrepo-com.svg
    - lib/images/abramov.webp
    - lib/images/krizh.jpeg
    - lib/images/stoika.jpg